/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicTermsRouteImport } from './routes/(public)/terms'
import { Route as publicPrivacyRouteImport } from './routes/(public)/privacy'
import { Route as publicappsPostsIndexRouteImport } from './routes/(public)/(apps)/posts.index'
import { Route as publicappsFeedsIndexRouteImport } from './routes/(public)/(apps)/feeds.index'
import { Route as publicappsworkWorkIndexRouteImport } from './routes/(public)/(apps)/(work)/work.index'
import { Route as publicappsusersAuthIndexRouteImport } from './routes/(public)/(apps)/(users)/auth.index'
import { Route as publicappsmessagesMessagesIndexRouteImport } from './routes/(public)/(apps)/(messages)/messages.index'
import { Route as publicappsusersAuthVerifyRouteImport } from './routes/(public)/(apps)/(users)/auth.verify'
import { Route as publicappsusersAuthPasswordSetupRouteImport } from './routes/(public)/(apps)/(users)/auth.password-setup'
import { Route as publicappsworkWorkVacanciesIndexRouteImport } from './routes/(public)/(apps)/(work)/work.vacancies.index'
import { Route as publicappsworkWorkCompaniesIndexRouteImport } from './routes/(public)/(apps)/(work)/work.companies.index'
import { Route as publicappsmessagesMessagesGroupsIndexRouteImport } from './routes/(public)/(apps)/(messages)/messages.groups.index'
import { Route as publicappsmessagesMessagesChatsIndexRouteImport } from './routes/(public)/(apps)/(messages)/messages.chats.index'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicTermsRoute = publicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicPrivacyRoute = publicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicappsPostsIndexRoute = publicappsPostsIndexRouteImport.update({
  id: '/(apps)/posts/',
  path: '/posts/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicappsFeedsIndexRoute = publicappsFeedsIndexRouteImport.update({
  id: '/(apps)/feeds/',
  path: '/feeds/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicappsworkWorkIndexRoute = publicappsworkWorkIndexRouteImport.update({
  id: '/(apps)/(work)/work/',
  path: '/work/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicappsusersAuthIndexRoute =
  publicappsusersAuthIndexRouteImport.update({
    id: '/(apps)/(users)/auth/',
    path: '/auth/',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicappsmessagesMessagesIndexRoute =
  publicappsmessagesMessagesIndexRouteImport.update({
    id: '/(apps)/(messages)/messages/',
    path: '/messages/',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicappsusersAuthVerifyRoute =
  publicappsusersAuthVerifyRouteImport.update({
    id: '/(apps)/(users)/auth/verify',
    path: '/auth/verify',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicappsusersAuthPasswordSetupRoute =
  publicappsusersAuthPasswordSetupRouteImport.update({
    id: '/(apps)/(users)/auth/password-setup',
    path: '/auth/password-setup',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicappsworkWorkVacanciesIndexRoute =
  publicappsworkWorkVacanciesIndexRouteImport.update({
    id: '/(apps)/(work)/work/vacancies/',
    path: '/work/vacancies/',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicappsworkWorkCompaniesIndexRoute =
  publicappsworkWorkCompaniesIndexRouteImport.update({
    id: '/(apps)/(work)/work/companies/',
    path: '/work/companies/',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicappsmessagesMessagesGroupsIndexRoute =
  publicappsmessagesMessagesGroupsIndexRouteImport.update({
    id: '/(apps)/(messages)/messages/groups/',
    path: '/messages/groups/',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicappsmessagesMessagesChatsIndexRoute =
  publicappsmessagesMessagesChatsIndexRouteImport.update({
    id: '/(apps)/(messages)/messages/chats/',
    path: '/messages/chats/',
    getParentRoute: () => publicRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/privacy': typeof publicPrivacyRoute
  '/terms': typeof publicTermsRoute
  '/': typeof publicIndexRoute
  '/feeds/': typeof publicappsFeedsIndexRoute
  '/posts/': typeof publicappsPostsIndexRoute
  '/auth/password-setup': typeof publicappsusersAuthPasswordSetupRoute
  '/auth/verify': typeof publicappsusersAuthVerifyRoute
  '/messages/': typeof publicappsmessagesMessagesIndexRoute
  '/auth/': typeof publicappsusersAuthIndexRoute
  '/work/': typeof publicappsworkWorkIndexRoute
  '/messages/chats/': typeof publicappsmessagesMessagesChatsIndexRoute
  '/messages/groups/': typeof publicappsmessagesMessagesGroupsIndexRoute
  '/work/companies/': typeof publicappsworkWorkCompaniesIndexRoute
  '/work/vacancies/': typeof publicappsworkWorkVacanciesIndexRoute
}
export interface FileRoutesByTo {
  '/privacy': typeof publicPrivacyRoute
  '/terms': typeof publicTermsRoute
  '/': typeof publicIndexRoute
  '/feeds': typeof publicappsFeedsIndexRoute
  '/posts': typeof publicappsPostsIndexRoute
  '/auth/password-setup': typeof publicappsusersAuthPasswordSetupRoute
  '/auth/verify': typeof publicappsusersAuthVerifyRoute
  '/messages': typeof publicappsmessagesMessagesIndexRoute
  '/auth': typeof publicappsusersAuthIndexRoute
  '/work': typeof publicappsworkWorkIndexRoute
  '/messages/chats': typeof publicappsmessagesMessagesChatsIndexRoute
  '/messages/groups': typeof publicappsmessagesMessagesGroupsIndexRoute
  '/work/companies': typeof publicappsworkWorkCompaniesIndexRoute
  '/work/vacancies': typeof publicappsworkWorkVacanciesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/(public)/privacy': typeof publicPrivacyRoute
  '/(public)/terms': typeof publicTermsRoute
  '/(public)/': typeof publicIndexRoute
  '/(public)/(apps)/feeds/': typeof publicappsFeedsIndexRoute
  '/(public)/(apps)/posts/': typeof publicappsPostsIndexRoute
  '/(public)/(apps)/(users)/auth/password-setup': typeof publicappsusersAuthPasswordSetupRoute
  '/(public)/(apps)/(users)/auth/verify': typeof publicappsusersAuthVerifyRoute
  '/(public)/(apps)/(messages)/messages/': typeof publicappsmessagesMessagesIndexRoute
  '/(public)/(apps)/(users)/auth/': typeof publicappsusersAuthIndexRoute
  '/(public)/(apps)/(work)/work/': typeof publicappsworkWorkIndexRoute
  '/(public)/(apps)/(messages)/messages/chats/': typeof publicappsmessagesMessagesChatsIndexRoute
  '/(public)/(apps)/(messages)/messages/groups/': typeof publicappsmessagesMessagesGroupsIndexRoute
  '/(public)/(apps)/(work)/work/companies/': typeof publicappsworkWorkCompaniesIndexRoute
  '/(public)/(apps)/(work)/work/vacancies/': typeof publicappsworkWorkVacanciesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/privacy'
    | '/terms'
    | '/'
    | '/feeds/'
    | '/posts/'
    | '/auth/password-setup'
    | '/auth/verify'
    | '/messages/'
    | '/auth/'
    | '/work/'
    | '/messages/chats/'
    | '/messages/groups/'
    | '/work/companies/'
    | '/work/vacancies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/privacy'
    | '/terms'
    | '/'
    | '/feeds'
    | '/posts'
    | '/auth/password-setup'
    | '/auth/verify'
    | '/messages'
    | '/auth'
    | '/work'
    | '/messages/chats'
    | '/messages/groups'
    | '/work/companies'
    | '/work/vacancies'
  id:
    | '__root__'
    | '/(public)'
    | '/(public)/privacy'
    | '/(public)/terms'
    | '/(public)/'
    | '/(public)/(apps)/feeds/'
    | '/(public)/(apps)/posts/'
    | '/(public)/(apps)/(users)/auth/password-setup'
    | '/(public)/(apps)/(users)/auth/verify'
    | '/(public)/(apps)/(messages)/messages/'
    | '/(public)/(apps)/(users)/auth/'
    | '/(public)/(apps)/(work)/work/'
    | '/(public)/(apps)/(messages)/messages/chats/'
    | '/(public)/(apps)/(messages)/messages/groups/'
    | '/(public)/(apps)/(work)/work/companies/'
    | '/(public)/(apps)/(work)/work/vacancies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/terms': {
      id: '/(public)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof publicTermsRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/privacy': {
      id: '/(public)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof publicPrivacyRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/(apps)/posts/': {
      id: '/(public)/(apps)/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof publicappsPostsIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/(apps)/feeds/': {
      id: '/(public)/(apps)/feeds/'
      path: '/feeds'
      fullPath: '/feeds/'
      preLoaderRoute: typeof publicappsFeedsIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/(apps)/(work)/work/': {
      id: '/(public)/(apps)/(work)/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof publicappsworkWorkIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/(apps)/(users)/auth/': {
      id: '/(public)/(apps)/(users)/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof publicappsusersAuthIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/(apps)/(messages)/messages/': {
      id: '/(public)/(apps)/(messages)/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof publicappsmessagesMessagesIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/(apps)/(users)/auth/verify': {
      id: '/(public)/(apps)/(users)/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof publicappsusersAuthVerifyRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/(apps)/(users)/auth/password-setup': {
      id: '/(public)/(apps)/(users)/auth/password-setup'
      path: '/auth/password-setup'
      fullPath: '/auth/password-setup'
      preLoaderRoute: typeof publicappsusersAuthPasswordSetupRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/(apps)/(work)/work/vacancies/': {
      id: '/(public)/(apps)/(work)/work/vacancies/'
      path: '/work/vacancies'
      fullPath: '/work/vacancies/'
      preLoaderRoute: typeof publicappsworkWorkVacanciesIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/(apps)/(work)/work/companies/': {
      id: '/(public)/(apps)/(work)/work/companies/'
      path: '/work/companies'
      fullPath: '/work/companies/'
      preLoaderRoute: typeof publicappsworkWorkCompaniesIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/(apps)/(messages)/messages/groups/': {
      id: '/(public)/(apps)/(messages)/messages/groups/'
      path: '/messages/groups'
      fullPath: '/messages/groups/'
      preLoaderRoute: typeof publicappsmessagesMessagesGroupsIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/(apps)/(messages)/messages/chats/': {
      id: '/(public)/(apps)/(messages)/messages/chats/'
      path: '/messages/chats'
      fullPath: '/messages/chats/'
      preLoaderRoute: typeof publicappsmessagesMessagesChatsIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
  }
}

interface publicRouteRouteChildren {
  publicPrivacyRoute: typeof publicPrivacyRoute
  publicTermsRoute: typeof publicTermsRoute
  publicIndexRoute: typeof publicIndexRoute
  publicappsFeedsIndexRoute: typeof publicappsFeedsIndexRoute
  publicappsPostsIndexRoute: typeof publicappsPostsIndexRoute
  publicappsusersAuthPasswordSetupRoute: typeof publicappsusersAuthPasswordSetupRoute
  publicappsusersAuthVerifyRoute: typeof publicappsusersAuthVerifyRoute
  publicappsmessagesMessagesIndexRoute: typeof publicappsmessagesMessagesIndexRoute
  publicappsusersAuthIndexRoute: typeof publicappsusersAuthIndexRoute
  publicappsworkWorkIndexRoute: typeof publicappsworkWorkIndexRoute
  publicappsmessagesMessagesChatsIndexRoute: typeof publicappsmessagesMessagesChatsIndexRoute
  publicappsmessagesMessagesGroupsIndexRoute: typeof publicappsmessagesMessagesGroupsIndexRoute
  publicappsworkWorkCompaniesIndexRoute: typeof publicappsworkWorkCompaniesIndexRoute
  publicappsworkWorkVacanciesIndexRoute: typeof publicappsworkWorkVacanciesIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicPrivacyRoute: publicPrivacyRoute,
  publicTermsRoute: publicTermsRoute,
  publicIndexRoute: publicIndexRoute,
  publicappsFeedsIndexRoute: publicappsFeedsIndexRoute,
  publicappsPostsIndexRoute: publicappsPostsIndexRoute,
  publicappsusersAuthPasswordSetupRoute: publicappsusersAuthPasswordSetupRoute,
  publicappsusersAuthVerifyRoute: publicappsusersAuthVerifyRoute,
  publicappsmessagesMessagesIndexRoute: publicappsmessagesMessagesIndexRoute,
  publicappsusersAuthIndexRoute: publicappsusersAuthIndexRoute,
  publicappsworkWorkIndexRoute: publicappsworkWorkIndexRoute,
  publicappsmessagesMessagesChatsIndexRoute:
    publicappsmessagesMessagesChatsIndexRoute,
  publicappsmessagesMessagesGroupsIndexRoute:
    publicappsmessagesMessagesGroupsIndexRoute,
  publicappsworkWorkCompaniesIndexRoute: publicappsworkWorkCompaniesIndexRoute,
  publicappsworkWorkVacanciesIndexRoute: publicappsworkWorkVacanciesIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
