/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicTermsRouteImport } from './routes/(public)/terms'
import { Route as publicPrivacyRouteImport } from './routes/(public)/privacy'
import { Route as usersAuthIndexRouteImport } from './routes/(users)/auth.index'
import { Route as usersAuthVerifyRouteImport } from './routes/(users)/auth.verify'
import { Route as usersAuthPasswordSetupRouteImport } from './routes/(users)/auth.password-setup'
import { Route as publicjobsJobsIndexRouteImport } from './routes/(public)/(jobs)/jobs.index'
import { Route as publiccommunityCommunityIndexRouteImport } from './routes/(public)/(community)/community.index'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicTermsRoute = publicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicPrivacyRoute = publicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => publicRouteRoute,
} as any)
const usersAuthIndexRoute = usersAuthIndexRouteImport.update({
  id: '/(users)/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const usersAuthVerifyRoute = usersAuthVerifyRouteImport.update({
  id: '/(users)/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const usersAuthPasswordSetupRoute = usersAuthPasswordSetupRouteImport.update({
  id: '/(users)/auth/password-setup',
  path: '/auth/password-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const publicjobsJobsIndexRoute = publicjobsJobsIndexRouteImport.update({
  id: '/(jobs)/jobs/',
  path: '/jobs/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publiccommunityCommunityIndexRoute =
  publiccommunityCommunityIndexRouteImport.update({
    id: '/(community)/community/',
    path: '/community/',
    getParentRoute: () => publicRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/privacy': typeof publicPrivacyRoute
  '/terms': typeof publicTermsRoute
  '/': typeof publicIndexRoute
  '/auth/password-setup': typeof usersAuthPasswordSetupRoute
  '/auth/verify': typeof usersAuthVerifyRoute
  '/auth/': typeof usersAuthIndexRoute
  '/community/': typeof publiccommunityCommunityIndexRoute
  '/jobs/': typeof publicjobsJobsIndexRoute
}
export interface FileRoutesByTo {
  '/privacy': typeof publicPrivacyRoute
  '/terms': typeof publicTermsRoute
  '/': typeof publicIndexRoute
  '/auth/password-setup': typeof usersAuthPasswordSetupRoute
  '/auth/verify': typeof usersAuthVerifyRoute
  '/auth': typeof usersAuthIndexRoute
  '/community': typeof publiccommunityCommunityIndexRoute
  '/jobs': typeof publicjobsJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/(public)/privacy': typeof publicPrivacyRoute
  '/(public)/terms': typeof publicTermsRoute
  '/(public)/': typeof publicIndexRoute
  '/(users)/auth/password-setup': typeof usersAuthPasswordSetupRoute
  '/(users)/auth/verify': typeof usersAuthVerifyRoute
  '/(users)/auth/': typeof usersAuthIndexRoute
  '/(public)/(community)/community/': typeof publiccommunityCommunityIndexRoute
  '/(public)/(jobs)/jobs/': typeof publicjobsJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/privacy'
    | '/terms'
    | '/'
    | '/auth/password-setup'
    | '/auth/verify'
    | '/auth/'
    | '/community/'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/privacy'
    | '/terms'
    | '/'
    | '/auth/password-setup'
    | '/auth/verify'
    | '/auth'
    | '/community'
    | '/jobs'
  id:
    | '__root__'
    | '/(public)'
    | '/(public)/privacy'
    | '/(public)/terms'
    | '/(public)/'
    | '/(users)/auth/password-setup'
    | '/(users)/auth/verify'
    | '/(users)/auth/'
    | '/(public)/(community)/community/'
    | '/(public)/(jobs)/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
  usersAuthPasswordSetupRoute: typeof usersAuthPasswordSetupRoute
  usersAuthVerifyRoute: typeof usersAuthVerifyRoute
  usersAuthIndexRoute: typeof usersAuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/terms': {
      id: '/(public)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof publicTermsRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/privacy': {
      id: '/(public)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof publicPrivacyRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(users)/auth/': {
      id: '/(users)/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof usersAuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(users)/auth/verify': {
      id: '/(users)/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof usersAuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(users)/auth/password-setup': {
      id: '/(users)/auth/password-setup'
      path: '/auth/password-setup'
      fullPath: '/auth/password-setup'
      preLoaderRoute: typeof usersAuthPasswordSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(jobs)/jobs/': {
      id: '/(public)/(jobs)/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof publicjobsJobsIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/(community)/community/': {
      id: '/(public)/(community)/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof publiccommunityCommunityIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
  }
}

interface publicRouteRouteChildren {
  publicPrivacyRoute: typeof publicPrivacyRoute
  publicTermsRoute: typeof publicTermsRoute
  publicIndexRoute: typeof publicIndexRoute
  publiccommunityCommunityIndexRoute: typeof publiccommunityCommunityIndexRoute
  publicjobsJobsIndexRoute: typeof publicjobsJobsIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicPrivacyRoute: publicPrivacyRoute,
  publicTermsRoute: publicTermsRoute,
  publicIndexRoute: publicIndexRoute,
  publiccommunityCommunityIndexRoute: publiccommunityCommunityIndexRoute,
  publicjobsJobsIndexRoute: publicjobsJobsIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
  usersAuthPasswordSetupRoute: usersAuthPasswordSetupRoute,
  usersAuthVerifyRoute: usersAuthVerifyRoute,
  usersAuthIndexRoute: usersAuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
