/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicTermsRouteImport } from './routes/(public)/terms'
import { Route as publicPrivacyRouteImport } from './routes/(public)/privacy'
import { Route as appsPostsIndexRouteImport } from './routes/(apps)/posts.index'
import { Route as appsFeedsIndexRouteImport } from './routes/(apps)/feeds.index'
import { Route as appsworkWorkIndexRouteImport } from './routes/(apps)/(work)/work.index'
import { Route as appsusersAuthIndexRouteImport } from './routes/(apps)/(users)/auth.index'
import { Route as appsmessagesMessagesIndexRouteImport } from './routes/(apps)/(messages)/messages.index'
import { Route as appsusersAuthVerifyRouteImport } from './routes/(apps)/(users)/auth.verify'
import { Route as appsusersAuthPasswordSetupRouteImport } from './routes/(apps)/(users)/auth.password-setup'
import { Route as appsworkWorkVacanciesIndexRouteImport } from './routes/(apps)/(work)/work.vacancies.index'
import { Route as appsworkWorkCompaniesIndexRouteImport } from './routes/(apps)/(work)/work.companies.index'
import { Route as appsmessagesMessagesGroupsIndexRouteImport } from './routes/(apps)/(messages)/messages.groups.index'
import { Route as appsmessagesMessagesChatsIndexRouteImport } from './routes/(apps)/(messages)/messages.chats.index'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicTermsRoute = publicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicPrivacyRoute = publicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => publicRouteRoute,
} as any)
const appsPostsIndexRoute = appsPostsIndexRouteImport.update({
  id: '/(apps)/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const appsFeedsIndexRoute = appsFeedsIndexRouteImport.update({
  id: '/(apps)/feeds/',
  path: '/feeds/',
  getParentRoute: () => rootRouteImport,
} as any)
const appsworkWorkIndexRoute = appsworkWorkIndexRouteImport.update({
  id: '/(apps)/(work)/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const appsusersAuthIndexRoute = appsusersAuthIndexRouteImport.update({
  id: '/(apps)/(users)/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const appsmessagesMessagesIndexRoute =
  appsmessagesMessagesIndexRouteImport.update({
    id: '/(apps)/(messages)/messages/',
    path: '/messages/',
    getParentRoute: () => rootRouteImport,
  } as any)
const appsusersAuthVerifyRoute = appsusersAuthVerifyRouteImport.update({
  id: '/(apps)/(users)/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const appsusersAuthPasswordSetupRoute =
  appsusersAuthPasswordSetupRouteImport.update({
    id: '/(apps)/(users)/auth/password-setup',
    path: '/auth/password-setup',
    getParentRoute: () => rootRouteImport,
  } as any)
const appsworkWorkVacanciesIndexRoute =
  appsworkWorkVacanciesIndexRouteImport.update({
    id: '/(apps)/(work)/work/vacancies/',
    path: '/work/vacancies/',
    getParentRoute: () => rootRouteImport,
  } as any)
const appsworkWorkCompaniesIndexRoute =
  appsworkWorkCompaniesIndexRouteImport.update({
    id: '/(apps)/(work)/work/companies/',
    path: '/work/companies/',
    getParentRoute: () => rootRouteImport,
  } as any)
const appsmessagesMessagesGroupsIndexRoute =
  appsmessagesMessagesGroupsIndexRouteImport.update({
    id: '/(apps)/(messages)/messages/groups/',
    path: '/messages/groups/',
    getParentRoute: () => rootRouteImport,
  } as any)
const appsmessagesMessagesChatsIndexRoute =
  appsmessagesMessagesChatsIndexRouteImport.update({
    id: '/(apps)/(messages)/messages/chats/',
    path: '/messages/chats/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/privacy': typeof publicPrivacyRoute
  '/terms': typeof publicTermsRoute
  '/': typeof publicIndexRoute
  '/feeds/': typeof appsFeedsIndexRoute
  '/posts/': typeof appsPostsIndexRoute
  '/auth/password-setup': typeof appsusersAuthPasswordSetupRoute
  '/auth/verify': typeof appsusersAuthVerifyRoute
  '/messages/': typeof appsmessagesMessagesIndexRoute
  '/auth/': typeof appsusersAuthIndexRoute
  '/work/': typeof appsworkWorkIndexRoute
  '/messages/chats/': typeof appsmessagesMessagesChatsIndexRoute
  '/messages/groups/': typeof appsmessagesMessagesGroupsIndexRoute
  '/work/companies/': typeof appsworkWorkCompaniesIndexRoute
  '/work/vacancies/': typeof appsworkWorkVacanciesIndexRoute
}
export interface FileRoutesByTo {
  '/privacy': typeof publicPrivacyRoute
  '/terms': typeof publicTermsRoute
  '/': typeof publicIndexRoute
  '/feeds': typeof appsFeedsIndexRoute
  '/posts': typeof appsPostsIndexRoute
  '/auth/password-setup': typeof appsusersAuthPasswordSetupRoute
  '/auth/verify': typeof appsusersAuthVerifyRoute
  '/messages': typeof appsmessagesMessagesIndexRoute
  '/auth': typeof appsusersAuthIndexRoute
  '/work': typeof appsworkWorkIndexRoute
  '/messages/chats': typeof appsmessagesMessagesChatsIndexRoute
  '/messages/groups': typeof appsmessagesMessagesGroupsIndexRoute
  '/work/companies': typeof appsworkWorkCompaniesIndexRoute
  '/work/vacancies': typeof appsworkWorkVacanciesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/(public)/privacy': typeof publicPrivacyRoute
  '/(public)/terms': typeof publicTermsRoute
  '/(public)/': typeof publicIndexRoute
  '/(apps)/feeds/': typeof appsFeedsIndexRoute
  '/(apps)/posts/': typeof appsPostsIndexRoute
  '/(apps)/(users)/auth/password-setup': typeof appsusersAuthPasswordSetupRoute
  '/(apps)/(users)/auth/verify': typeof appsusersAuthVerifyRoute
  '/(apps)/(messages)/messages/': typeof appsmessagesMessagesIndexRoute
  '/(apps)/(users)/auth/': typeof appsusersAuthIndexRoute
  '/(apps)/(work)/work/': typeof appsworkWorkIndexRoute
  '/(apps)/(messages)/messages/chats/': typeof appsmessagesMessagesChatsIndexRoute
  '/(apps)/(messages)/messages/groups/': typeof appsmessagesMessagesGroupsIndexRoute
  '/(apps)/(work)/work/companies/': typeof appsworkWorkCompaniesIndexRoute
  '/(apps)/(work)/work/vacancies/': typeof appsworkWorkVacanciesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/privacy'
    | '/terms'
    | '/'
    | '/feeds/'
    | '/posts/'
    | '/auth/password-setup'
    | '/auth/verify'
    | '/messages/'
    | '/auth/'
    | '/work/'
    | '/messages/chats/'
    | '/messages/groups/'
    | '/work/companies/'
    | '/work/vacancies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/privacy'
    | '/terms'
    | '/'
    | '/feeds'
    | '/posts'
    | '/auth/password-setup'
    | '/auth/verify'
    | '/messages'
    | '/auth'
    | '/work'
    | '/messages/chats'
    | '/messages/groups'
    | '/work/companies'
    | '/work/vacancies'
  id:
    | '__root__'
    | '/(public)'
    | '/(public)/privacy'
    | '/(public)/terms'
    | '/(public)/'
    | '/(apps)/feeds/'
    | '/(apps)/posts/'
    | '/(apps)/(users)/auth/password-setup'
    | '/(apps)/(users)/auth/verify'
    | '/(apps)/(messages)/messages/'
    | '/(apps)/(users)/auth/'
    | '/(apps)/(work)/work/'
    | '/(apps)/(messages)/messages/chats/'
    | '/(apps)/(messages)/messages/groups/'
    | '/(apps)/(work)/work/companies/'
    | '/(apps)/(work)/work/vacancies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
  appsFeedsIndexRoute: typeof appsFeedsIndexRoute
  appsPostsIndexRoute: typeof appsPostsIndexRoute
  appsusersAuthPasswordSetupRoute: typeof appsusersAuthPasswordSetupRoute
  appsusersAuthVerifyRoute: typeof appsusersAuthVerifyRoute
  appsmessagesMessagesIndexRoute: typeof appsmessagesMessagesIndexRoute
  appsusersAuthIndexRoute: typeof appsusersAuthIndexRoute
  appsworkWorkIndexRoute: typeof appsworkWorkIndexRoute
  appsmessagesMessagesChatsIndexRoute: typeof appsmessagesMessagesChatsIndexRoute
  appsmessagesMessagesGroupsIndexRoute: typeof appsmessagesMessagesGroupsIndexRoute
  appsworkWorkCompaniesIndexRoute: typeof appsworkWorkCompaniesIndexRoute
  appsworkWorkVacanciesIndexRoute: typeof appsworkWorkVacanciesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/terms': {
      id: '/(public)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof publicTermsRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/privacy': {
      id: '/(public)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof publicPrivacyRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(apps)/posts/': {
      id: '/(apps)/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof appsPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(apps)/feeds/': {
      id: '/(apps)/feeds/'
      path: '/feeds'
      fullPath: '/feeds/'
      preLoaderRoute: typeof appsFeedsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(apps)/(work)/work/': {
      id: '/(apps)/(work)/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof appsworkWorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(apps)/(users)/auth/': {
      id: '/(apps)/(users)/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof appsusersAuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(apps)/(messages)/messages/': {
      id: '/(apps)/(messages)/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof appsmessagesMessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(apps)/(users)/auth/verify': {
      id: '/(apps)/(users)/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof appsusersAuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(apps)/(users)/auth/password-setup': {
      id: '/(apps)/(users)/auth/password-setup'
      path: '/auth/password-setup'
      fullPath: '/auth/password-setup'
      preLoaderRoute: typeof appsusersAuthPasswordSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(apps)/(work)/work/vacancies/': {
      id: '/(apps)/(work)/work/vacancies/'
      path: '/work/vacancies'
      fullPath: '/work/vacancies/'
      preLoaderRoute: typeof appsworkWorkVacanciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(apps)/(work)/work/companies/': {
      id: '/(apps)/(work)/work/companies/'
      path: '/work/companies'
      fullPath: '/work/companies/'
      preLoaderRoute: typeof appsworkWorkCompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(apps)/(messages)/messages/groups/': {
      id: '/(apps)/(messages)/messages/groups/'
      path: '/messages/groups'
      fullPath: '/messages/groups/'
      preLoaderRoute: typeof appsmessagesMessagesGroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(apps)/(messages)/messages/chats/': {
      id: '/(apps)/(messages)/messages/chats/'
      path: '/messages/chats'
      fullPath: '/messages/chats/'
      preLoaderRoute: typeof appsmessagesMessagesChatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface publicRouteRouteChildren {
  publicPrivacyRoute: typeof publicPrivacyRoute
  publicTermsRoute: typeof publicTermsRoute
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicPrivacyRoute: publicPrivacyRoute,
  publicTermsRoute: publicTermsRoute,
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
  appsFeedsIndexRoute: appsFeedsIndexRoute,
  appsPostsIndexRoute: appsPostsIndexRoute,
  appsusersAuthPasswordSetupRoute: appsusersAuthPasswordSetupRoute,
  appsusersAuthVerifyRoute: appsusersAuthVerifyRoute,
  appsmessagesMessagesIndexRoute: appsmessagesMessagesIndexRoute,
  appsusersAuthIndexRoute: appsusersAuthIndexRoute,
  appsworkWorkIndexRoute: appsworkWorkIndexRoute,
  appsmessagesMessagesChatsIndexRoute: appsmessagesMessagesChatsIndexRoute,
  appsmessagesMessagesGroupsIndexRoute: appsmessagesMessagesGroupsIndexRoute,
  appsworkWorkCompaniesIndexRoute: appsworkWorkCompaniesIndexRoute,
  appsworkWorkVacanciesIndexRoute: appsworkWorkVacanciesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
